export enum ROLES {
  TEST = 'TEST',
  PUBLISHER = 'PUBLISHER',
  'ACCOUNT MANAGER' = 'ACCOUNT MANAGER',
  'SENIOR ACCOUNT MANAGER' = 'SENIOR ACCOUNT MANAGER',
  'ANALYTICS BOT' = 'ANALYTICS BOT',
  'CEO MANAGE' = 'CEO MANAGE',
  CEO = 'CEO',
  'MEDIA BUYER' = 'MEDIA BUYER',
  'WBID ANALYTICS USER' = 'WBID ANALYTICS USER',
  ADMIN = 'ADMIN',
  'AD OPS' = 'AD OPS',
  MANAGER_SENIOR = 'SENIOR ACCOUNT MANAGER',
  PARTNER = 'oRTB Partner',
  'FINANCE_MANAGER' = 'FINANCE MANAGER'
}
