import { Types } from 'mongoose';

const users = [
  {
    _id: Types.ObjectId('5fd9dc21af4ae2d75536f7d6'),
    commission: {
      commission_number: '0',
      commission_type: 'no data'
    },
    name: 'admin-laslo',
    email: 'admin@admin.admin',
    password: '$2b$10$OIPlV3OFGE7mN22kwPZ5NelLP9U.EjjGcvRXfz7JJ4r.beR7fuQZG',
    enabled: {
      changed: false,
      status: true
    },
    role: 'ADMIN',
    is_test: false,
    permissions: [
      'canSeeDashboardPage',
      'canSeeSettingsPage',
      'canAddAllUsers',
      'canSeeUsersPage',
      'canSeePermissionManager',
      'canReadAllUsers',
      'canEditAllUsers',
      'canDeleteAllUsers',
      'canToggleUsers',
      'canReadAllReports',
      'canSeeCodesPage',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canAddReports',
      'canReadOwnAccountInfo',
      'canSeeReportManagementPage',
      'canReadPermissions',
      'canReadPreviouslyUploadedReports',
      'canDeletePreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeAPIManagementPage',
      'canDeleteReports',
      'canSeeWBidPage',
      'canDeleteWBidPlacements',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canCreateWBidPlacements',
      'canEditWBidPlacements',
      'canDeleteWBidSites',
      'canEditWBidSites',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSetWBidShortTag',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSetWBidMarketplace',
      'canSeeAllWBidUsers',
      'canSeeWBidStatusAdsTxt',
      'canEditOwnPermissions',
      'canUseAPIAccessForReports',
      'canReadAllDeductions',
      'canReadAllWBidReports',
      'canCreateVideoTag',
      'canSeeCodesVideoPage',
      'canReadAllTacReports',
      'canReadOwnTacReports',
      'canCreateTacCodes',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canCreateNewAdUnit',
      'canSetPublisherForVideoTag',
      'canSetManagerForVideoTag',
      'canCreateDevConfigs',
      'canReadOwnPubs',
      'canUpdateVplCDN',
      'canSeeUsersToolsPage',
      'canDeleteOwnNotice',
      'canReadOwnNotices',
      'canSeeInvoicesPage',
      'canUploadInvoices',
      'canEditInvoiceStatus',
      'canSeeAllInvoices',
      'canDeleteInvoices',
      'canCreateNotification',
      'canAddCustomNotification',
      'canEditCommission',
      'canAddDeduction',
      'canSeeAdsTxtPage',
      'canDownloadInvoices',
      'canGenerateRefLink',
      'canReadAllOrtbReports',
      'canReadOwnOrtbReports',
      'canReadAllPubs',
      'canAddOwnPubs',
      'canAddAllPubs',
      'canReadOwnDomains',
      'canEditAllPubs',
      'canEditOwnPubs',
      'canReadOwnPubsReports',
      'canReadAllPubsReports',
      'canReadOwnReports',
      'canAddOwnPubsReports',
      'canReadOwnDeductions',
      'canReadOwnAndAccountDeductions',
      'canSeeOwnInvoices',
      'canReadWBidOwnPubsReports',
      'canReadWBidAllPubsReports',
      'canReadOwnPublishersDeductions',
      'canSeeRevenues',
      'canEditRevenues',
      'canDeleteRevenues',
      'canSeeRevenuePage',
      'canEditVersion',
      'canSeeDSPoRTBReports',
      'canSeeSSPoRTBReports',
      'erewre',
      '111111111',
      'canConnectUnitWithPub'
    ],
    domains: [],
    updatedAt: '2021-06-15T12:24:39.959Z',
    createdAt: '2018-03-29T15:24:51.881Z',
    photo: 'b787cf3e-f119-4754-bbed-fcaa462e7a19.jpeg',
    am: null,
    connected_users: {
      p: [],
      am: []
    },
    sam: null,
    additional: {
      company: 'WMG Inc.',
      phone: '',
      skype: '',
      address: '',
      birthday: '1994-01-24T22:00:00Z',
      description: ''
    },
    previouslyUploadedReports: [
      Types.ObjectId('60ab8d260fd596004dcd41ab'),
      Types.ObjectId('60ab887e0fd596004dcd41aa'),
      Types.ObjectId('609b97399f13b6003a8662ee'),
      Types.ObjectId('6078079dff239e4bf40e88eb'),
      Types.ObjectId('605e08df8f42490020e4921b'),
      Types.ObjectId('605e08df8f42490020e4921c'),
      Types.ObjectId('605e08df8f42490020e4921d'),
      Types.ObjectId('6050cde62d596b00286dcfe0'),
      Types.ObjectId('6050cb0d2d596b00286dcfdf'),
      Types.ObjectId('6050ca793fe5a43490cbeaee'),
      Types.ObjectId('604b670d877a9d002b4abd4e'),
      Types.ObjectId('603e238d3b92850023c5e372'),
      Types.ObjectId('6037baf9542609002cba4d43'),
      Types.ObjectId('60266a74843c5149008f122a'),
      Types.ObjectId('5f748cedbae17123d0a548fc'),
      Types.ObjectId('5f748b556f59a837e85bccfd'),
      Types.ObjectId('5f74822550d41636c8216992'),
      Types.ObjectId('5f746d8160456d3c4046b758'),
      Types.ObjectId('5f746563f1a27e06902aea3e'),
      Types.ObjectId('5f7463ecd27cf92e40663a39')
    ],
    uuid: 'fef95c8e-5dcc-4942-b1a2-a1a37735db05',
    cwe: null,
    generatedReport: '244e41a5-4eb0-4f5a-a7a6-14bcce0f3832',
    properties: [],
    wBidderUser: false,
    wbidType: [],
    wbidUserId: null
  },
  {
    _id: Types.ObjectId('5fe1d84f152b8b3da8e67dd6'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canAddAllUsers',
      'canSeeUsersPage',
      'canSeePermissionManager',
      'canReadAllUsers',
      'canEditAllUsers',
      'canDeleteAllUsers',
      'canToggleUsers',
      'canReadAllReports',
      'canSeeCodesPage',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeReportManagementPage',
      'canSeeSettingsPage',
      'canReadPermissions',
      'canReadPreviouslyUploadedReports',
      'canDeletePreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeAPIManagementPage',
      'canDeleteReports',
      'canSeeWBidPage',
      'canDeleteWBidPlacements',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canCreateWBidPlacements',
      'canEditWBidPlacements',
      'canDeleteWBidSites',
      'canEditWBidSites',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSetWBidShortTag',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSetWBidMarketplace',
      'canSeeAllWBidUsers',
      'canSeeWBidStatusAdsTxt',
      'canPreviewWBidPlacements',
      'canUseAPIAccessForReports',
      'canReadAllDeductions',
      'canReadAllWBidReports',
      'canCreateVideoTag',
      'canSeeCodesVideoPage',
      'canReadAllTacReports',
      'canReadOwnTacReports',
      'canCreateTacCodes',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canCreateNewAdUnit',
      'canSetPublisherForVideoTag',
      'canSetManagerForVideoTag',
      'canCreateDevConfigs',
      'canReadOwnPubs',
      'canUpdateVplCDN',
      'canSeeUsersToolsPage',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canUploadInvoices',
      'canEditInvoiceStatus',
      'canSeeAllInvoices',
      'canDeleteInvoices',
      'canCreateNotification',
      'canAddCustomNotification',
      'canEditCommission',
      'canAddDeduction',
      'canSeeAdsTxtPage',
      'canDownloadInvoices',
      'canGenerateRefLink',
      'canReadOwnNotices',
      'canReadAllOrtbReports',
      'canAddReports',
      'canSeeRevenues',
      'canEditRevenues',
      'canDeleteRevenues',
      'canSeeRevenuePage',
      'canEditVersion',
      'canSeeDSPoRTBReports',
      'canSeeSSPoRTBReports',
      'erewre',
      '111111111',
      'canConnectUnitWithPub'
    ],
    domains: [],
    cwe: true,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [
      Types.ObjectId('6088251c9c56635b9c6e6fb7'),
      Types.ObjectId('608824b09c56635b9c6e6fb6'),
      Types.ObjectId('60782042a32e5d9c71702fd6'),
      Types.ObjectId('60781f3a5c48e29becce4946'),
      Types.ObjectId('60781871c2f62e9b6d3fcb68'),
      Types.ObjectId('60781307204b6e98aa2233d2'),
      Types.ObjectId('604b4587b122b26cd97c0c77')
    ],
    wbidType: [],
    wbidUserId: null,
    name: 'Vladislav Hirsa',
    role: 'ADMIN',
    is_test: false,
    email: 'v.hirsa@adwmg.com',
    password: '$2b$10$wTs4J4ZByQFWZTfg7oiTRutRyycp8D46WoCHW6H.20YuNoZrDi.Bu',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '55618f11-2802-40d1-84c3-75decaea5f9d',
    properties: [],
    updatedAt: '2021-06-09T08:40:17.971Z',
    createdAt: '2020-12-22T11:28:15.672Z',
    generatedReport: 'd6860fb7-b7db-43bd-91f1-0bef5c02029c'
  },
  {
    _id: Types.ObjectId('601191b537f7b920ac0d33cc'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canAddAllUsers',
      'canSeeUsersPage',
      'canSeePermissionManager',
      'canReadAllUsers',
      'canEditAllUsers',
      'canDeleteAllUsers',
      'canToggleUsers',
      'canReadAllReports',
      'canSeeCodesPage',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canAddReports',
      'canReadOwnAccountInfo',
      'canSeeReportManagementPage',
      'canSeeSettingsPage',
      'canReadPermissions',
      'canReadPreviouslyUploadedReports',
      'canDeletePreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeAPIManagementPage',
      'canDeleteReports',
      'canSeeWBidPage',
      'canDeleteWBidPlacements',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canCreateWBidPlacements',
      'canEditWBidPlacements',
      'canDeleteWBidSites',
      'canEditWBidSites',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSetWBidShortTag',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSetWBidMarketplace',
      'canSeeAllWBidUsers',
      'canSeeWBidStatusAdsTxt',
      'canPreviewWBidPlacements',
      'canUseAPIAccessForReports',
      'canReadAllDeductions',
      'canReadAllWBidReports',
      'canCreateVideoTag',
      'canSeeCodesVideoPage',
      'canReadAllTacReports',
      'canReadOwnTacReports',
      'canCreateTacCodes',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canCreateNewAdUnit',
      'canSetPublisherForVideoTag',
      'canSetManagerForVideoTag',
      'canCreateDevConfigs',
      'canReadOwnPubs',
      'canUpdateVplCDN',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canUploadInvoices',
      'canEditInvoiceStatus',
      'canSeeAllInvoices',
      'canDeleteInvoices',
      'canCreateNotification',
      'canAddCustomNotification',
      'canEditCommission',
      'canAddDeduction',
      'canSeeAdsTxtPage',
      'canDownloadInvoices',
      'canGenerateRefLink',
      'canReadAllOrtbReports',
      'canSeeRevenues',
      'canEditRevenues',
      'canDeleteRevenues',
      'canSeeRevenuePage',
      'canEditVersion',
      'canSeeDSPoRTBReports',
      'canSeeSSPoRTBReports',
      'erewre',
      '111111111',
      'canConnectUnitWithPub'
    ],
    domains: [],
    cwe: null,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'test_acc_design',
    role: 'ADMIN',
    is_test: false,
    email: 'dreemvn@gmail.com',
    password: '$2b$10$xMpX2Kkr9I/7XMQuFj1XP.Ejxj.4jDKWS1izGuilcbv5fjRe02dUm',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '74bcb9f4-3ad3-427c-b4cf-f10e0429ebe7',
    properties: [],
    updatedAt: '2021-01-27T16:15:49.057Z',
    createdAt: '2021-01-27T16:15:49.057Z'
  },
  {
    _id: Types.ObjectId('6051d6246529d8002b097ec8'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canAddAllUsers',
      'canSeeUsersPage',
      'canSeePermissionManager',
      'canReadAllUsers',
      'canEditAllUsers',
      'canDeleteAllUsers',
      'canToggleUsers',
      'canReadAllReports',
      'canSeeCodesPage',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canAddReports',
      'canReadOwnAccountInfo',
      'canSeeReportManagementPage',
      'canSeeSettingsPage',
      'canReadPermissions',
      'canReadPreviouslyUploadedReports',
      'canDeletePreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeAPIManagementPage',
      'canDeleteReports',
      'canSeeWBidPage',
      'canDeleteWBidPlacements',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canCreateWBidPlacements',
      'canEditWBidPlacements',
      'canDeleteWBidSites',
      'canEditWBidSites',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSetWBidShortTag',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSetWBidMarketplace',
      'canSeeAllWBidUsers',
      'canSeeWBidStatusAdsTxt',
      'canPreviewWBidPlacements',
      'canUseAPIAccessForReports',
      'canReadAllDeductions',
      'canReadAllWBidReports',
      'canCreateVideoTag',
      'canSeeCodesVideoPage',
      'canReadAllTacReports',
      'canReadOwnTacReports',
      'canCreateTacCodes',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canCreateNewAdUnit',
      'canSetPublisherForVideoTag',
      'canSetManagerForVideoTag',
      'canCreateDevConfigs',
      'canReadOwnPubs',
      'canUpdateVplCDN',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canUploadInvoices',
      'canEditInvoiceStatus',
      'canSeeAllInvoices',
      'canDeleteInvoices',
      'canCreateNotification',
      'canAddCustomNotification',
      'canEditCommission',
      'canAddDeduction',
      'canSeeAdsTxtPage',
      'canDownloadInvoices',
      'canGenerateRefLink',
      'canReadAllOrtbReports',
      'canReadOwnOrtbReports',
      'canSeeOwnInvoices',
      'canReadWBidOwnPubsReports',
      'canReadWBidAllPubsReports',
      'canReadOwnPublishersDeductions',
      'canReadOwnAndAccountDeductions',
      'canReadOwnDeductions',
      'canEditOwnPermissions',
      'canEditAllPubs',
      'canEditOwnPubs',
      'canAddAllPubs',
      'canSeeOwnWBidSettings',
      'canSeeOwnWBidUsers',
      'canAddOwnPubsReports',
      'canReadOwnReports',
      'canReadAllPubsReports',
      'canReadOwnPubsReports',
      'canReadOwnDomains',
      'canSeeRevenues',
      'canEditRevenues',
      'canDeleteRevenues',
      'canSeeRevenuePage',
      'canEditVersion',
      'canSeeDSPoRTBReports',
      'canSeeSSPoRTBReports',
      'erewre',
      '111111111',
      'canConnectUnitWithPub'
    ],
    domains: [],
    cwe: null,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [Types.ObjectId('60521c1bd5d97c002d3a985c')],
    wbidType: [],
    wbidUserId: null,
    name: 'admin2',
    role: 'ADMIN',
    is_test: false,
    email: 'admin2@admin.admin',
    password: '$2b$10$7dJrD7qQwuedmpYQCGScJ.mr3UJh8gCkDfkjnS0s/u8KOm8CZFW6.',
    additional: {
      company: 'Windows XP SP3',
      phone: '1234',
      skype: 'test',
      address: '',
      birthday: null,
      description: 'pass: 12345678'
    },
    uuid: '3dbd4c22-bc2d-4e2d-aee6-51355315d139',
    properties: [],
    updatedAt: '2021-03-17T10:12:52.866Z',
    createdAt: '2021-03-17T10:12:52.866Z'
  },
  {
    _id: Types.ObjectId('5fd9e3ddaf4ae2d75536f7d7'),
    connected_users: {
      p: [],
      am: []
    },
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    permissions: [
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canDownloadReports',
      'hideRequestsAndFillrate',
      'firstMay',
      null,
      'canSeeDashboardPage',
      'canAddAllUsers',
      'canSeeSettingsPage',
      'canReadOwnDomains',
      'canSeeUsersPage',
      'canUseAPIAccessForReports',
      'canReadOwnDeductions',
      'canReadAllPubs',
      'canSeePermissionManager',
      'canReadOwnReports',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canUpdateVplCDN',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canUploadInvoices',
      'canSeeOwnInvoices',
      'canDownloadInvoices',
      'canDeleteInvoices',
      'canReadOwnOrtbReports',
      'canReadOwnNotices',
      'canSeeRevenues',
      'canSeeRevenuePage'
    ],
    domains: [],
    am: Types.ObjectId('6001425e00f80f4688b50a3e'),
    sam: null,
    name: 'mail.ru',
    role: 'PUBLISHER',
    is_test: false,
    email: 'mail@mail.mail',
    password: '$2b$10$n/WHBKbxBYF/ncfmsKPaleVP5c5JdanO1Sdrfkhrs8snAS3brDmMi',
    properties: [
      {
        _id: Types.ObjectId('60c75f293c70bc3dc847a50c'),
        placement_name: 'ok.ru_300x250',
        property_id: '300x250',
        property_description: null,
        property_origin: 'Smart'
      },
      {
        _id: Types.ObjectId('60c75f293c70bc3dc847a50d'),
        placement_name: 'ok.ru_300x250',
        property_id: 'ok.ru_300x250',
        property_description: null,
        property_origin: 'Smart'
      },
      {
        _id: Types.ObjectId('60c75f293c70bc3dc847a50e'),
        placement_name: 'ok.ru_300x250',
        property_id: 'ok.ru_300x250_leftpanel',
        property_description: '',
        property_origin: 'Smart'
      },
      {
        _id: Types.ObjectId('60a228036b85c8026825bead'),
        placement_name: 'HBGAM',
        property_id: 'ok.ru_300x600_HB_4_OW',
        property_description: null,
        property_origin: 'AppNexus'
      },
      {
        _id: Types.ObjectId('60a228036b85c8026825beae'),
        placement_name: 'HBGAM',
        property_id: 'e.mail.ru_300x250_HB_3_OW',
        property_description: '',
        property_origin: 'AppNexus'
      },
      {
        _id: Types.ObjectId('6086ab8f3f5c3d4b7caf60ff'),
        placement_name: 'mail.ru_160x600',
        property_id: 'lady.mail.ru_240x400_HB_1_OW',
        property_description: null,
        property_origin: 'AppNexus'
      },
      {
        _id: Types.ObjectId('6086ab8f3f5c3d4b7caf6100'),
        placement_name: 'mail.ru_160x600',
        property_id: 'my.mail.ru_240x400_HB_OW',
        property_description: null,
        property_origin: 'AppNexus'
      },
      {
        _id: Types.ObjectId('6086ab8f3f5c3d4b7caf6101'),
        placement_name: 'mail.ru_160x600',
        property_id: 'mail.ru_970x90_HB',
        property_description: '',
        property_origin: 'AppNexus'
      },
      {
        _id: Types.ObjectId('6082ffdbec7cc04b8085b14f'),
        placement_name: 'HBGAM',
        property_id: 'lady_mail_ru_240x400_HB_2',
        property_description: null,
        property_origin: 'Google Ad Manager HB'
      },
      {
        _id: Types.ObjectId('6082ffdbec7cc04b8085b150'),
        placement_name: 'HBGAM',
        property_id: 'lady_mail_ru_240x400_HB_1',
        property_description: '',
        property_origin: 'Google Ad Manager HB'
      },
      {
        _id: Types.ObjectId('6080a7cbe5fdd04538559e11'),
        placement_name: 'rtb_plcmnt',
        property_id: 'ok_ru_left_panel_1_300x250',
        property_description: null,
        property_origin: 'RTB House'
      },
      {
        _id: Types.ObjectId('6080a7cbe5fdd04538559e12'),
        placement_name: 'rtb_plcmnt',
        property_id: 'pogoda_mail_ru_2_300x250',
        property_description: null,
        property_origin: 'RTB House'
      },
      {
        _id: Types.ObjectId('6080a7cbe5fdd04538559e13'),
        placement_name: 'rtb_plcmnt',
        property_id: 'new_mail_ru_2_300x250',
        property_description: '',
        property_origin: 'RTB House'
      },
      {
        _id: Types.ObjectId('6040e56e644dd44f24e8ebd8'),
        placement_name: 'EPlaning',
        property_id: 'ok.ru_300x600_0',
        property_description: '',
        property_origin: 'E-Planning'
      },
      {
        _id: Types.ObjectId('603e48e019400f074c818c15'),
        placement_name: 'Google_HB_plcmnt',
        property_id: 'deti.mail.ru_240x400_postbid_hgmbgi3sz',
        property_description: '',
        property_origin: 'Google Ad Manager HB'
      },
      {
        _id: Types.ObjectId('603e2f7585e4b84c2845c6fa'),
        placement_name: 'mail.ru_160x600',
        property_id: 'mail_ru_mobile_300x250_HB',
        property_description: '',
        property_origin: 'Google Ad Manager HB'
      },
      {
        _id: Types.ObjectId('603e1c7ccb402f0ce085cf65'),
        placement_name: 'mail.ru_160x600',
        property_id: '7184-e.mail.ru_160x600',
        property_description: '',
        property_origin: 'Criteo'
      },
      {
        _id: Types.ObjectId('603d1abf28303146b8439394'),
        placement_name: 'Google_HB_plcmnt',
        property_id: '160x600_mail.ru_new',
        property_description: null,
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('603d1abf28303146b8439395'),
        placement_name: 'Google_HB_plcmnt',
        property_id: 'moevideo_inStream',
        property_description: null,
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('603d1a9728303146b843936d'),
        placement_name: 'Google_HB_plcmnt',
        property_id: 'auto.mail.ru_240x400_new',
        property_description: null,
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('603d1a9728303146b843936e'),
        placement_name: 'Google_HB_plcmnt',
        property_id: '160x600_mail.ru',
        property_description: null,
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('6038c05f002a8146c4c768ea'),
        placement_name: 'EPlaning',
        property_id: 'mail.ru_320x50_0',
        property_description: null,
        property_origin: 'E-Planning'
      },
      {
        _id: Types.ObjectId('6038c05f002a8146c4c768eb'),
        placement_name: 'EPlaning',
        property_id: 'mail.ru_300x250_0',
        property_description: null,
        property_origin: 'E-Planning'
      },
      {
        _id: Types.ObjectId('6038c05f002a8146c4c768ec'),
        placement_name: 'EPlaning',
        property_id: 'tv.mail.ru_300x250_0',
        property_description: null,
        property_origin: 'E-Planning'
      },
      {
        _id: Types.ObjectId('6038c05f002a8146c4c768ed'),
        placement_name: 'EPlaning',
        property_id: 'e.mail.ru_300x250_0',
        property_description: '',
        property_origin: 'E-Planning'
      },
      {
        _id: Types.ObjectId('603568f77556e9073031149e'),
        placement_name: 'mail.ru_160x600',
        property_id: 'games.ok.ru_300x600_0',
        property_description: null,
        property_origin: 'E-Planning'
      },
      {
        _id: Types.ObjectId('603568f77556e9073031149f'),
        placement_name: 'mail.ru_160x600',
        property_id: 'mail.ru_320x50_0',
        property_description: '',
        property_origin: 'E-Planning'
      },
      {
        _id: Types.ObjectId('6033d838e8738c5390d0bcf6'),
        placement_name: 'Criteo_plcmnt',
        property_id: '10169-ok.ru_300x600',
        property_description: '',
        property_origin: 'Criteo'
      },
      {
        _id: Types.ObjectId('5fe1c17ad69ada1d7cbf1bf8'),
        placement_name: 'Criteo_plcmnt',
        property_id: '7184-tv.mail.ru_300x250',
        property_description: '',
        property_origin: 'Criteo'
      },
      {
        _id: Types.ObjectId('5fe1bb6f4de0fe499438af80'),
        placement_name: 'mail.ru_160x600',
        property_id: '/112081842/amazon_post_bid/Amazon_mail.ru_short_tag_160x600_postbid_tusqikitx',
        property_description: null,
        property_origin: 'Amazon'
      },
      {
        _id: Types.ObjectId('5fe1bb6f4de0fe499438af81'),
        placement_name: 'mail.ru_160x600',
        property_id: '160x600_mail.ru',
        property_description: null,
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5fe1bb6f4de0fe499438af82'),
        placement_name: 'ok.ru 240x400',
        property_id: 'ok.ru_240x400_HB_3_OW',
        property_description: null,
        property_origin: 'AppNexus'
      },
      {
        _id: Types.ObjectId('5fe1bb6f4de0fe499438af84'),
        placement_name: 'MyTarget',
        property_id: '721482_mail.ru',
        property_description: null,
        property_origin: 'MyTarget'
      },
      {
        _id: Types.ObjectId('5fe1bb6f4de0fe499438af85'),
        placement_name: 'mail.ru_160x600',
        property_id: 'e_mail.ru_160x600_WB',
        property_description: '',
        property_origin: 'PubMatic'
      },
      {
        _id: Types.ObjectId('5fda02c834a22a3d88577ec9'),
        placement_name: 'ok.ru 240x400',
        property_id: 'Ok.ru_240x400',
        property_description: '',
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5fcf5faf42f28b023c9da593'),
        placement_name: 'ok.ru_160x600',
        property_id: 'ok.ru_160x600_new',
        property_description: '',
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5fcf4d1302357b294c5db365'),
        placement_name: 'news.mail.ru_240x400',
        property_id: 'news.mail.ru_240x400_new',
        property_description: '',
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5f8eff12974e8e09d89398a0'),
        placement_name: 'ok.ru_160x600',
        property_id: 'ok_ru_160x600_postbid_0rjy7hb4i',
        property_description: null,
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5f8eff12974e8e09d893989f'),
        placement_name: 'ok.ru_160x600',
        property_id: 'ok_ru_160x600_HB_1',
        property_description: '',
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5f885e9bd4370f1630320869'),
        placement_name: 'pubmat_plcmnt',
        property_id: '728x90_news.mail.ru',
        property_description: '',
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5f4cf4cee8d13c374497cbfa'),
        placement_name: 'rtb_plcmnt',
        property_id: 'ok_ru_disc_1_300x250',
        property_description: null,
        property_origin: 'RTB House'
      },
      {
        _id: Types.ObjectId('5f4cf4cee8d13c374497cbf9'),
        placement_name: 'rtb_plcmnt',
        property_id: 'e.mail.ru_1_300x250',
        property_description: '',
        property_origin: 'RTB House'
      },
      {
        _id: Types.ObjectId('5f4ce3811440113470e371b3'),
        placement_name: 'rtb_plcmnt',
        property_id: 'ok_ru_left_panel_2_300x250',
        property_description: null,
        property_origin: 'RTB House'
      },
      {
        _id: Types.ObjectId('5f4ce3811440113470e371b2'),
        placement_name: 'rtb_plcmnt',
        property_id: 'mail.ru_short_tag_160x600',
        property_description: '',
        property_origin: 'RTB House'
      },
      {
        _id: Types.ObjectId('5f4ce0e9bee7c72cc4c30931'),
        placement_name: 'Criteo_plcmnt',
        property_id: '7184-horo.mail.ru_240x400',
        property_description: null,
        property_origin: 'Criteo'
      },
      {
        _id: Types.ObjectId('5f4ce0e9bee7c72cc4c30930'),
        placement_name: 'Criteo_plcmnt',
        property_id: '7184-ok.ru_240x400',
        property_description: '',
        property_origin: 'Criteo'
      },
      {
        _id: Types.ObjectId('5f4cc5e78c131b533c978e0a'),
        placement_name: 'Criteo_plcmnt',
        property_id: '7184-realty.mail.ru_300x250',
        property_description: null,
        property_origin: 'Criteo'
      },
      {
        _id: Types.ObjectId('5f4cc5e78c131b533c978e09'),
        placement_name: 'Criteo_plcmnt',
        property_id: '7184-health.mail.ru_300x250',
        property_description: '',
        property_origin: 'Criteo'
      },
      {
        _id: Types.ObjectId('5f48bedd550fe23e703a0251'),
        placement_name: 'pubmat_plcmnt',
        property_id: 'news_mail.ru_300x250_WB_1',
        property_description: '',
        property_origin: 'PubMatic'
      },
      {
        _id: Types.ObjectId('5f1e9a11301ad30924e6d862'),
        placement_name: 'mail.ru_160x600',
        property_id: '160x600_mail.ru_new',
        property_description: '',
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5f1e85e87e364409dcb8af77'),
        placement_name: 'Ok.ru_pre-rolls',
        property_id: '/112081842/main_mail_ru_300x250_HB',
        property_description: null,
        property_origin: 'Amazon'
      },
      {
        _id: Types.ObjectId('5f1e80582998603cd47595c0'),
        placement_name: 'mail.ru_160x600',
        property_id: 'e.mail.ru_160x600_postbid_7qgtgqpwp',
        property_description: null,
        property_origin: 'Google Ad Manager HB'
      },
      {
        _id: Types.ObjectId('5f1e7fc52998603cd47595bc'),
        placement_name: 'mail.ru_160x600',
        property_id: 'e_mail_ru_160x600_HB_1',
        property_description: '',
        property_origin: 'Google Ad Manager HB'
      },
      {
        _id: Types.ObjectId('5f1e7e0c2998603cd47595b7'),
        placement_name: 'mail.ru_160x600',
        property_id: '/112081842/amazon_post_bid/Amazon_e.mail.ru_160x600_postbid_vbp45j67m',
        property_description: '',
        property_origin: 'Amazon'
      },
      {
        _id: Types.ObjectId('5f16d4b3e3dd105b28786ceb'),
        placement_name: 'Ok.ru_pre-rolls',
        property_id: 'Ok.ru_all_rolls',
        property_description: '',
        property_origin: 'Google Ad Manager'
      }
    ],
    updatedAt: '2021-06-14T13:52:41.322Z',
    createdAt: '2021-03-31T21:00:00Z',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    cwe: true,
    previouslyUploadedReports: [],
    uuid: '8d667932-a993-44b2-99c5-a4c42aa60f5b',
    wbidType: [],
    wbidUserId: null,
    date_to_connect_am: '2021-06-10T08:01:16Z'
  },
  {
    _id: Types.ObjectId('5fdb3d3f36efda18b4b1701a'),
    commission: {
      commission_number: 35,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: false
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'hideRequestsAndFillrate',
      'canSeeDashboardPage',
      'canReadOwnDomains',
      'canAddAllUsers',
      'canSeeUsersPage',
      'canUseAPIAccessForReports',
      'canReadOwnDeductions',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canUpdateVplCDN',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canUploadInvoices',
      'canSeeOwnInvoices',
      'canReadOwnReports',
      'canDownloadReports',
      'canDownloadInvoices',
      'canDeleteInvoices',
      'canReadOwnOrtbReports',
      'canReadOwnNotices',
      'canSeeRevenues',
      'canSeeRevenuePage'
    ],
    domains: [],
    cwe: true,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'publisher_change',
    role: 'PUBLISHER',
    is_test: true,
    email: 'pub@pub.pub',
    password: '$2b$10$3H9QzdSLxi5d8v/uFqlREusWt/LmMKYIIjQTjFm/UPLXh1hC1g6gC',
    additional: {
      company: 's',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '2526268b-a3c6-490f-b98f-c9cd1c6c6a6e',
    properties: [
      {
        _id: Types.ObjectId('5fdcbd2edac7c530a0f544a5'),
        placement_name: 'absolutesmmpanel.com_336x280',
        property_id: 'absolutesmmpanel.com_336x280_1_vb',
        property_description: null,
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5fdcbd2edac7c530a0f544a6'),
        placement_name: 'absolutesmmpanel.com_336x280',
        property_id: 'absolutesmmpanel.com_336x280_3_vb_vast',
        property_description: null,
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5fdcbd2edac7c530a0f544a7'),
        placement_name: 'absolutesmmpanel.com_336x280',
        property_id: 'absolutesmmpanel.com_336x280_5_vb',
        property_description: null,
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5fdcbd2edac7c530a0f544a8'),
        placement_name: 'absolutesmmpanel.com_300x250',
        property_id: 'absolutesmmpanel.com_300x250_vb_vast',
        property_description: null,
        property_origin: 'Google Ad Manager'
      },
      {
        _id: Types.ObjectId('5fdcbd2edac7c530a0f544a9'),
        placement_name: 'absolutesmmpanel.com_336x280',
        property_id: 'absolutesmmpanel.com_336x280_1_vb_vast',
        property_description: '',
        property_origin: 'Google Ad Manager'
      }
    ],
    updatedAt: '2020-12-18T16:44:23.093Z',
    createdAt: '2020-12-17T11:13:03.549Z'
  },
  {
    _id: Types.ObjectId('5fdcbb46c7d6ff1da4fb4392'),
    commission: {
      commission_number: 30,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'hideRequestsAndFillrate',
      'canSeeDashboardPage',
      'canReadOwnDomains',
      'canAddAllUsers',
      'canSeeUsersPage',
      'canUseAPIAccessForReports',
      'canReadOwnDeductions',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canUpdateVplCDN',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canUploadInvoices',
      'canSeeOwnInvoices',
      'canReadOwnReports',
      'canDownloadReports',
      'canDownloadInvoices',
      'canDeleteInvoices',
      'canReadOwnOrtbReports',
      'canReadOwnNotices',
      'canSeeRevenues',
      'canSeeRevenuePage'
    ],
    domains: [],
    cwe: null,
    am: Types.ObjectId('602cd4f220654b36b48fb696'),
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'pub01',
    role: 'PUBLISHER',
    is_test: false,
    email: 'publisher@adwmg.com',
    password: '$2b$10$U6VAjB4FjJGiNVcscBju0eWlcAshlpBlUS9AxIMCb8hhQ365TtHM2',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '8d38905a-3cc4-4451-9ab2-db5bdd928e48',
    properties: [],
    updatedAt: '2020-12-18T14:23:02.226Z',
    createdAt: '2020-12-18T14:23:02.226Z'
  },
  {
    _id: Types.ObjectId('5fdcc70472fae243a47b784f'),
    commission: {
      commission_number: 30,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'hideRequestsAndFillrate',
      'canSeeDashboardPage',
      'canReadOwnDomains',
      'canAddAllUsers',
      'canSeeUsersPage',
      'canUseAPIAccessForReports',
      'canReadOwnDeductions',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canUpdateVplCDN',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canUploadInvoices',
      'canSeeOwnInvoices',
      'canReadOwnReports',
      'canDownloadReports',
      'canDownloadInvoices',
      'canDeleteInvoices',
      'canReadOwnOrtbReports',
      'canReadOwnNotices',
      'canSeeRevenues',
      'canSeeRevenuePage'
    ],
    domains: [],
    cwe: null,
    am: Types.ObjectId('5ff43848f428a44ffc88f165'),
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'publisher_new_dom',
    role: 'PUBLISHER',
    is_test: true,
    email: 'dom@dom.dom',
    password: '$2b$10$r91pGLbMiwRuq0inbk3XtOns4cza9Woj6xac82JhLS6ECd9Cg87Ia',
    additional: {
      company: 'as',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '3f0f5d2f-fd3d-42b1-8633-da79edd9ed2f',
    properties: [
      {
        _id: Types.ObjectId('5fe5f195c94225577c6104de'),
        placement_name: 'rbc.ru_300x600',
        property_description: '',
        property_origin: 'RTB House',
        property_id: 'rbc_1_short_300x600'
      },
      {
        _id: Types.ObjectId('5fe5f9c3c26b293f6c579d75'),
        placement_name: 'rbc.ru_300x600',
        property_description: '',
        property_id: 'rbc.ru_300x600_254248',
        property_origin: 'Rubicon'
      },
      {
        _id: Types.ObjectId('5fe5f9c3c26b293f6c579d74'),
        placement_name: 'rbc.ru_300x250',
        property_description: '',
        property_id: 'rbc.ru_300x250_254248',
        property_origin: 'Rubicon'
      }
    ],
    updatedAt: '2020-12-25T14:52:09.044Z',
    createdAt: '2020-12-18T15:13:09.088Z'
  },
  {
    _id: Types.ObjectId('5fdcdceba2418c45d855a377'),
    commission: {
      commission_number: 30,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'hideRequestsAndFillrate',
      'canSeeDashboardPage',
      'canReadOwnDomains',
      'canAddAllUsers',
      'canSeeUsersPage',
      'canUseAPIAccessForReports',
      'canReadOwnDeductions',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canUpdateVplCDN',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canUploadInvoices',
      'canSeeOwnInvoices',
      'canReadOwnReports',
      'canDownloadReports',
      'canDownloadInvoices',
      'canDeleteInvoices',
      'canReadOwnOrtbReports',
      'canReadOwnNotices',
      'canSeeRevenues',
      'canSeeRevenuePage'
    ],
    domains: [],
    cwe: null,
    am: Types.ObjectId('602cd4f220654b36b48fb696'),
    sam: null,
    date_to_connect_am: '2021-02-17T00:00:00Z',
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'publisher_domains',
    role: 'PUBLISHER',
    is_test: false,
    email: 'd@d.dd',
    password: '$2b$10$iqNLDjcPQFOkdL3.1cl6o.tME0OGr978pzy7qlOzHNSjqcJm3oR7a',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '2427d4a7-e207-49f6-8ea4-0b82762917a3',
    properties: [],
    updatedAt: '2020-12-18T16:46:35.116Z',
    createdAt: '2020-12-18T16:46:35.116Z'
  },
  {
    _id: Types.ObjectId('5ff43848f428a44ffc88f165'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [
        Types.ObjectId('5fdcbb46c7d6ff1da4fb4392'),
        Types.ObjectId('5fec6762405f1f0918b080fa'),
        Types.ObjectId('607807047bab23078037d1d0'),
        Types.ObjectId('5fe1cf8dd9d6b4366495fa9d'),
        Types.ObjectId('5fe1cf8dd9d6b4366495fa9d'),
        Types.ObjectId('5ff3128e499c651e306aa97e'),
        Types.ObjectId('5ff3128e499c651e306aa97e')
      ],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canSeeUsersPage',
      'canReadOwnPubs',
      'canReadOwnPubsReports',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'canReadPreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeWBidPage',
      'canSeeOwnWBidUsers',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSeeWBidStatusAdsTxt',
      'canUseAPIAccessForReports',
      'canReadOwnPublishersDeductions',
      'canReadWBidOwnPubsReports',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canSeeOwnInvoices',
      'canSeeAdsTxtPage',
      'canReadOwnOrtbReports',
      'canSeeRevenuePage'
    ],
    domains: [],
    cwe: true,
    am: null,
    sam: Types.ObjectId('5fe20f7f908754585419117a'),
    date_to_connect_am: '2021-01-05T00:00:00Z',
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'simple_acc',
    role: 'ACCOUNT MANAGER',
    is_test: false,
    email: 'acc@acc.acc',
    password: '$2b$10$rqRweK3U1uufapDncErEe.R0vbmktkjqlZwacIs.l7TUNCY6lufea',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '22adb51f-7ee3-4af1-a72f-b83cacd9e969',
    properties: [],
    updatedAt: '2021-04-26T16:25:16.139Z',
    createdAt: '2021-01-05T09:58:32.505Z',
    generatedReport: '271ef022-c343-49f7-97e0-b2e1351884b7'
  },
  {
    _id: Types.ObjectId('60014e4400f80f4688b50a3f'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [
        Types.ObjectId('60014ea400f80f4688b50a40'),
        Types.ObjectId('609259a894d0e7d6ca8528ca'),
        Types.ObjectId('609259a894d0e7d6ca8528ca')
      ],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canSeeUsersPage',
      'canReadOwnPubs',
      'canReadOwnPubsReports',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'canReadPreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeWBidPage',
      'canSeeOwnWBidUsers',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSeeWBidStatusAdsTxt',
      'canUseAPIAccessForReports',
      'canReadOwnPublishersDeductions',
      'canReadWBidOwnPubsReports',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canSeeOwnInvoices',
      'canSeeAdsTxtPage',
      'canReadOwnOrtbReports',
      'canSeeRevenuePage'
    ],
    domains: [],
    cwe: true,
    am: null,
    sam: Types.ObjectId('6001425e00f80f4688b50a3e'),
    date_to_connect_am: '2021-01-15T00:00:00Z',
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'account1',
    role: 'ACCOUNT MANAGER',
    is_test: true,
    email: 'acc1@adwmg.com',
    password: '$2b$10$AD85CSbitn.nks/W3b/Vx.UpFGAeq8ZBJBnEj1a1itcSZDg8gBGnm',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: 'dbae8bf7-f247-48db-a358-c0e6969c446e',
    properties: [],
    updatedAt: '2021-01-15T08:46:24.716Z',
    createdAt: '2021-01-15T08:11:48.375Z'
  },
  {
    _id: Types.ObjectId('602cd4f220654b36b48fb696'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [
        Types.ObjectId('5fdcdceba2418c45d855a377'),
        Types.ObjectId('5ff306fb499c651e306aa948'),
        Types.ObjectId('6026ae00cdd5de37d478a50b'),
        Types.ObjectId('5fdcbb46c7d6ff1da4fb4392')
      ],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canSeeUsersPage',
      'canReadOwnPubs',
      'canReadOwnPubsReports',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'canReadPreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeWBidPage',
      'canSeeOwnWBidUsers',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSeeWBidStatusAdsTxt',
      'canUseAPIAccessForReports',
      'canReadOwnPublishersDeductions',
      'canReadWBidOwnPubsReports',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canSeeOwnInvoices',
      'canSeeAdsTxtPage',
      'canReadOwnOrtbReports',
      'canSeeRevenuePage'
    ],
    domains: [],
    cwe: null,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'acc_for_tests',
    role: 'ACCOUNT MANAGER',
    is_test: false,
    email: 'acc@test.com',
    password: '$2b$10$iWQ.BBwmBKn0zcCPerW56ebyBzz8EYhbqg0hiVD.rP2JwSctldNOK',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '632b380b-c745-4171-99ec-7b593f5fbdc3',
    properties: [],
    updatedAt: '2021-02-17T08:35:20.770Z',
    createdAt: '2021-02-17T08:33:54.417Z'
  },
  {
    _id: Types.ObjectId('603f9c483b32680052260a52'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [
        Types.ObjectId('609259a894d0e7d6ca8528ca'),
        Types.ObjectId('609259a894d0e7d6ca8528ca'),
        Types.ObjectId('6022623c5633f32914714a93'),
        Types.ObjectId('6022623c5633f32914714a93')
      ],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canSeeUsersPage',
      'canReadOwnPubs',
      'canReadOwnPubsReports',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'canReadPreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeWBidPage',
      'canSeeOwnWBidUsers',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSeeWBidStatusAdsTxt',
      'canUseAPIAccessForReports',
      'canReadOwnPublishersDeductions',
      'canReadWBidOwnPubsReports',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canSeeOwnInvoices',
      'canSeeAdsTxtPage',
      'canReadOwnOrtbReports',
      'canSeeRevenuePage'
    ],
    domains: [],
    cwe: null,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'incognito_acc',
    role: 'ACCOUNT MANAGER',
    is_test: false,
    email: 'incognito_acc@gmail.com',
    password: '$2b$10$vSPh7cUNz.LL6rtisLSMXuii1BXpHkNsb6xzbaZonQEszAF2Ryk4i',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '0f9b0759-e6f7-4c7c-995c-b2bfb7fe7d6d',
    properties: [],
    updatedAt: '2021-03-03T14:25:12.961Z',
    createdAt: '2021-03-03T14:25:12.961Z'
  },
  {
    _id: Types.ObjectId('604a5207d655f08ae9f7cd44'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: false
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canSeeUsersPage',
      'canReadOwnPubs',
      'canReadOwnPubsReports',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'canReadPreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeWBidPage',
      'canSeeOwnWBidUsers',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSeeWBidStatusAdsTxt',
      'canUseAPIAccessForReports',
      'canReadOwnPublishersDeductions',
      'canReadWBidOwnPubsReports',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canSeeOwnInvoices',
      'canSeeAdsTxtPage',
      'canReadOwnOrtbReports',
      'canSeeRevenuePage'
    ],
    domains: [],
    cwe: null,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'minecraft',
    role: 'ACCOUNT MANAGER',
    is_test: true,
    email: 'lollo@lol.ol',
    password: '$2b$10$4jPjUTbC3JZJylMElp2Sr.X57Rq6lNQhNvco.m6TZpwWNpPV5JmN.',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '9d409bf6-4437-438c-81ac-67b117dcfabf',
    properties: [],
    updatedAt: '2021-03-23T15:32:46.340Z',
    createdAt: '2021-03-11T17:23:19.751Z'
  },
  {
    _id: Types.ObjectId('603f9c7e3b32680052260a53'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canSeeReportManagementPage',
      'canSeeSettingsPage',
      'canReadAllPubs',
      'canUploadAvatar',
      'canAddReports',
      'canReadOwnAccountInfo',
      'canReadPreviouslyUploadedReports',
      'canDeletePreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeUsersPage',
      'canSeeAPIManagementPage',
      'canAddAllUsers',
      'canEditAllPubs',
      'canReadAllUsers',
      'canAddAllPubs',
      'canReadAllReports',
      'canToggleUsers',
      'canSeeCodesPage',
      'canDeleteReports',
      'canSeeWBidPage',
      'canDeleteWBidPlacements',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canCreateWBidPlacements',
      'canEditWBidPlacements',
      'canDeleteWBidSites',
      'canEditWBidSites',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSetWBidShortTag',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSetWBidMarketplace',
      'canSeeAllWBidUsers',
      'canSeeWBidStatusAdsTxt',
      'canUseAPIAccessForReports',
      'canReadAllDeductions',
      'canReadAllWBidReports',
      'canReadAllTacReports',
      'canReadOwnTacReports',
      'canCreateTacCodes',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canCreateNewAdUnit',
      'canUpdateVplCDN',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canSeeAllInvoices',
      'canAddDeduction',
      'canSeeAdsTxtPage',
      'canReadAllOrtbReports',
      'canEditRevenues',
      'canSeeRevenuePage',
      'canConnectUnitWithPub'
    ],
    domains: [],
    cwe: null,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'incognito_ad',
    role: 'AD OPS',
    is_test: false,
    email: 'incognito_ad@gmail.com',
    password: '$2b$10$HFap9yxdLEmEruFjYm1A1eb/ntuX8rdeWPhTZ2.g8zInU2M50NIOO',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '17cdb8a9-8e42-4b66-84b0-931374424228',
    properties: [],
    updatedAt: '2021-03-03T14:26:06.119Z',
    createdAt: '2021-03-03T14:26:06.119Z'
  },
  {
    _id: Types.ObjectId('60a6200afdc609a488978eb8'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canSeeReportManagementPage',
      'canSeeSettingsPage',
      'canReadAllPubs',
      'canUploadAvatar',
      'canAddReports',
      'canReadOwnAccountInfo',
      'canReadPreviouslyUploadedReports',
      'canDeletePreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeUsersPage',
      'canSeeAPIManagementPage',
      'canAddAllUsers',
      'canEditAllPubs',
      'canReadAllUsers',
      'canAddAllPubs',
      'canReadAllReports',
      'canToggleUsers',
      'canSeeCodesPage',
      'canDeleteReports',
      'canSeeWBidPage',
      'canDeleteWBidPlacements',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canCreateWBidPlacements',
      'canEditWBidPlacements',
      'canDeleteWBidSites',
      'canEditWBidSites',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSetWBidShortTag',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSetWBidMarketplace',
      'canSeeAllWBidUsers',
      'canSeeWBidStatusAdsTxt',
      'canUseAPIAccessForReports',
      'canReadAllDeductions',
      'canReadAllWBidReports',
      'canReadAllTacReports',
      'canReadOwnTacReports',
      'canCreateTacCodes',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canCreateNewAdUnit',
      'canUpdateVplCDN',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canSeeAllInvoices',
      'canAddDeduction',
      'canSeeAdsTxtPage',
      'canReadAllOrtbReports',
      'canEditRevenues',
      'canSeeRevenuePage',
      'canConnectUnitWithPub'
    ],
    domains: [],
    cwe: null,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'loha-add-ops',
    role: 'AD OPS',
    is_test: false,
    email: 'loha-add-ops@add.add',
    password: '$2b$10$aQUUGfLB2Ia9eJK2tHk59.GzLJXN/nEO.bm9PYVShEcI87kZ/5ZpO',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: 'b03e3deb-545c-4bfc-8672-3c3ba3be8091',
    properties: [],
    updatedAt: '2021-05-20T08:38:34.690Z',
    createdAt: '2021-05-20T08:38:34.690Z'
  },
  {
    _id: Types.ObjectId('60afb1a3e208a474a0ea86f0'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [],
      am: []
    },
    permissions: [
      'canSeeDashboardPage',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canSeeReportManagementPage',
      'canSeeSettingsPage',
      'canReadAllPubs',
      'canUploadAvatar',
      'canAddReports',
      'canReadOwnAccountInfo',
      'canReadPreviouslyUploadedReports',
      'canDeletePreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeUsersPage',
      'canSeeAPIManagementPage',
      'canAddAllUsers',
      'canEditAllPubs',
      'canReadAllUsers',
      'canAddAllPubs',
      'canReadAllReports',
      'canToggleUsers',
      'canSeeCodesPage',
      'canDeleteReports',
      'canSeeWBidPage',
      'canDeleteWBidPlacements',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canCreateWBidPlacements',
      'canEditWBidPlacements',
      'canDeleteWBidSites',
      'canEditWBidSites',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSetWBidShortTag',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSetWBidMarketplace',
      'canSeeAllWBidUsers',
      'canSeeWBidStatusAdsTxt',
      'canUseAPIAccessForReports',
      'canReadAllDeductions',
      'canReadAllWBidReports',
      'canReadAllTacReports',
      'canReadOwnTacReports',
      'canCreateTacCodes',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canCreateNewAdUnit',
      'canUpdateVplCDN',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canSeeAllInvoices',
      'canAddDeduction',
      'canSeeAdsTxtPage',
      'canReadAllOrtbReports',
      'canEditRevenues',
      'canSeeRevenuePage',
      'canConnectUnitWithPub'
    ],
    domains: [],
    cwe: null,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'loha_ops',
    role: 'AD OPS',
    is_test: false,
    email: 'loha_ops@lohaops.com',
    password: '$2b$10$GhZOJrrxjs56QUvNXYkcvesx1XNb0Sl43Qih.bhoOAHP6QoaOf1MW',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: '1c9d6a64-7238-4a32-b535-28be6b621946',
    properties: [],
    updatedAt: '2021-05-27T14:50:11.494Z',
    createdAt: '2021-05-27T14:50:11.494Z'
  },
  {
    _id: Types.ObjectId('5fe20f7f908754585419117a'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: true
    },
    connected_users: {
      p: [
        Types.ObjectId('6018026664c5504ae8680389'),
        Types.ObjectId('6078179aeb7ec19b76fb5ed1'),
        Types.ObjectId('60781fcbf357e09c7b258575'),
        Types.ObjectId('602262605633f32914714a95'),
        Types.ObjectId('5ff3128e499c651e306aa97e'),
        Types.ObjectId('5ff30393499c651e306aa942'),
        Types.ObjectId('6061a9a206b2a24144e84585')
      ],
      am: [Types.ObjectId('5ff43848f428a44ffc88f165')]
    },
    permissions: [
      'canSeeDashboardPage',
      'canSeeUsersPage',
      'canReadAllPubs',
      'canReadAllPubsReports',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'canReadPreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeWBidPage',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSeeAllWBidUsers',
      'canSeeWBidStatusAdsTxt',
      'canUseAPIAccessForReports',
      'canReadOwnAndAccountDeductions',
      'canReadWBidAllPubsReports',
      'canReadAllTacReports',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canUpdateVplCDN',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canSeeAllInvoices',
      'canSeeAdsTxtPage',
      'canReadOwnOrtbReports',
      'canCreateNewAdUnit',
      'canSeeRevenuePage',
      '111111111',
      'canConnectUnitWithPub'
    ],
    domains: [],
    cwe: true,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'serious SAM',
    role: 'SENIOR ACCOUNT MANAGER',
    is_test: false,
    email: 'sam@sam.sam',
    password: '$2b$10$6JaLEXsajyVFXEYWujEecO0emc4qRIk8D.nsEJOtdJ4McdYZROWou',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: 'c740c4d9-2a62-479b-8d80-e54df9aadc6a',
    properties: [],
    updatedAt: '2021-06-23T14:57:10.228Z',
    createdAt: '2020-12-22T15:23:43.998Z',
    generatedReport: 'bf8141f6-d2b7-4aa0-babe-b19432c35deb',
    photo: '73a84730-596f-4947-aa74-34eea12f2337.png',
    adWMGAdapter: false
  },
  {
    _id: Types.ObjectId('6001425e00f80f4688b50a3e'),
    commission: {
      commission_number: 0,
      commission_type: 'eCPM'
    },
    enabled: {
      changed: false,
      status: false
    },
    connected_users: {
      p: [Types.ObjectId('60014ec200f80f4688b50a42'), Types.ObjectId('5fd9e3ddaf4ae2d75536f7d7')],
      am: [Types.ObjectId('60014e4400f80f4688b50a3f')]
    },
    permissions: [
      'canSeeDashboardPage',
      'canSeeUsersPage',
      'canReadAllPubs',
      'canReadAllPubsReports',
      'canSeeReportsPage',
      'canSeeOwnProfilePage',
      'canUploadAvatar',
      'canReadOwnAccountInfo',
      'canSeeSettingsPage',
      'canReadPreviouslyUploadedReports',
      'canDownloadReports',
      'canSeeWBidPage',
      'canSeeAnalyticsPage',
      'canSeeWBidChartsPage',
      'canSeeWBidTablesPage',
      'canSeeWBidAmazonSettings',
      'canSeeWBidSchainSettings',
      'canSeeWBidPrebidServerSettings',
      'canSeeWBidMarketplace',
      'canSeeWBidPlacementHistory',
      'canSeeWBidActions',
      'canSeeAllWBidUsers',
      'canSeeWBidStatusAdsTxt',
      'canUseAPIAccessForReports',
      'canReadOwnAndAccountDeductions',
      'canReadWBidAllPubsReports',
      'canReadAllTacReports',
      'canReadOwnTacReports',
      'canSeeTacReportsPage',
      'canGetAdUnit',
      'canUpdateVplCDN',
      'canSeeUsersToolsPage',
      'canReadOwnNotices',
      'canDeleteOwnNotice',
      'canSeeInvoicesPage',
      'canSeeAllInvoices',
      'canSeeAdsTxtPage',
      'canReadOwnOrtbReports',
      'canCreateNewAdUnit',
      'canSeeRevenuePage',
      '111111111',
      'canConnectUnitWithPub'
    ],
    domains: [],
    cwe: true,
    am: null,
    sam: null,
    date_to_connect_am: null,
    previouslyUploadedReports: [],
    wbidType: [],
    wbidUserId: null,
    name: 'senior-acc',
    role: 'SENIOR ACCOUNT MANAGER',
    is_test: true,
    email: 'senior@adwmg.com',
    password: '$2b$10$h/.P8q//Z1jDXp1sX1hWPeDDqsl4u/UVT7dNGrdsXGS3J5QswNRYe',
    additional: {
      company: '',
      phone: '',
      skype: '',
      address: '',
      birthday: null,
      description: ''
    },
    uuid: 'd8c445e2-8438-495c-8dc7-c15d663f84f8',
    properties: [],
    updatedAt: '2021-06-23T14:56:10.551Z',
    createdAt: '2021-01-15T07:21:02.780Z',
    adWMGAdapter: false
  }
];

export { users };
