export const Fields = {
  adagio: {
    domain: 'site',
    clicks: '',
    date: 'day',
    placement: 'placement',
    size: '',
    width: '',
    height: '',
    mediaType: 'BidMediatype',
    requests: 'adCalls',
    impressions: 'impressions',
    cpm: 'netCPM',
  },
  Amazon: {
    domain: 'Site',
    clicks: '',
    date: 'Date',
    placement: 'Slot',
    size: 'Size',
    width: '',
    height: '',
    mediaType: '',
    requests: 'Bid Requests',
    impressions: 'Impressions',
    cpm: 'eCPM',
  },
  Ampliffy: {},
  appnexus: {
    domain: '',
    clicks: 'Clicks',
    date: 'Day',
    placement: 'Placement',
    size: 'Size',
    width: '',
    height: '',
    mediaType: 'Media Type',
    requests: 'Impression Requests',
    impressions: 'Imps',
    cpm: 'Total RPM'
  },
  bRealTime: {
    domain: '',
    clicks: 'Clicks',
    date: 'Day',
    placement: 'Placement',
    size: 'Size',
    width: '',
    height: '',
    mediaType: 'Media Type',
    requests: 'Impression Requests',
    impressions: 'Imps',
    cpm: 'Publisher RPM (USD)'
  },
  GAM: {
    domain: 'Sites',
    clicks: 'Clicks',
    date: 'Days',
    placement: 'DFP Ad Units',
    size: 'Inventory sizes',
    width: '',
    height: '',
    mediaType: '',
    requests: 'Ad requests',
    impressions: 'Ad impressions',
    cpm: 'Ad eCPM ($)'
  },
  EMX: {
    domain: 'Domains',
    clicks: '',
    date: 'Date',
    placement: 'Ad Units',
    size: '',
    width: '',
    height: '',
    mediaType: '',
    requests: 'Ad Renders',
    impressions: '',
    cpm: 'Ad Render eCPM',
  },
  RTB_House: {
    domain: 'domain',
    clicks: '',
    date: '',
    placement: 'slot_name',
    size: 'size',
    width: '',
    height: '',
    mediaType: 'ad_type',
    requests: '',
    impressions: 'impressions',
    cpm: 'revenue'
  },
  Rubicon: {
    domain: 'Site URL',
    clicks: '',
    date: 'Date',
    placement: 'Site',
    size: 'Size',
    width: '',
    height: '',
    mediaType: 'Ad Format',
    requests: 'Ad Requests',
    impressions: 'Paid Impressions',
    cpm: 'eCPM',
  },
  Smart: {
    domain: 'Site URL',
    clicks: '',
    date: 'Time',
    placement: 'Name (Insertion)',
    size: '',
    width: 'Width (Format)',
    height: 'Height (Format)',
    mediaType: '',
    requests: 'RTB+ Auctions',
    impressions: 'RTB+ Impressions',
    cpm: 'RTB+ eCPM',
  },
  EPlanning: {
    domain: 'Site',
    clicks: '',
    date: 'Date',
    placement: '',
    size: '',
    width: '',
    height: '',
    mediaType: '',
    requests: 'Auctioned impressions',
    impressions: 'Impressions sold in auctions',
    cpm: 'eCPM',
  },
  OpenX: {
    domain: 'Page Domain',
    clicks: 'Clicks',
    date: 'Day',
    placement: 'Ad Unit Name',
    size: 'Ad Size',
    width: '',
    height: '',
    mediaType: 'Media Subtype',
    requests: 'All Requests',
    impressions: 'Paid/Billable Impressions',
    cpm: 'CPM (Pub Currency)',
  },
  OneTag: {
    domain: 'Site-BundleId',
    clicks: '',
    date: 'Day',
    placement: '',
    size: '',
    width: '',
    height: '',
    mediaType: '',
    requests: 'Incoming BidRequest',
    impressions: 'Paid Impression',
    cpm: 'CPM Earnings € (EUR)',
  },
  Criteo: {
    domain: 'Domain',
    clicks: 'Clicks',
    date: 'TimeId',
    placement: 'Subid',
    size: 'ZoneFormat',
    width: '',
    height: '',
    mediaType: '',
    requests: '',
    impressions: 'Criteo displays',
    cpm: 'CPM',
    specific: {
      zoneName: 'ZoneName',
      networkId: 'NetworkId'
    }
  },
  Yandex: {}
}

export type FieldsTypeObject = {
  width: string;
  height: string;
  domain: string,
  clicks: string,
  date: string,
  placement: string,
  size: string,
  mediaType: string,
  requests: string,
  impressions: string,
  cpm: string,
  specific?: any
}
